#!/bin/bash
#===================================================================================================
# CyborgAI
# CC BY-NC-ND 4.0 Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International
# github: https://github.com/cyborg-ai-git
#===================================================================================================
# Document Configuration
version = "v2025.11.151757"
title = "Evo Framework AI"
subtitle = "The fastest and secure framework for AI"
author = " "
#---------------------------------------------------------------------------------------------------
# Paths and Resources
logo = "./data/evo_framework.png"
output_dir = "./output"
template = "data/dark.tex"
emoji_config = "data/working_emoji.tex"
#---------------------------------------------------------------------------------------------------
# PDF Engine Options
pdf_engine = "xelatex"
enable_toc = true
number_sections = true
shell_escape = true
#===================================================================================================